### ISSUE TITLE
Multiple Monitor Video Capturing

### ISSUE THREAD

**Issue by truptigogad2** [mihaiparvu/ScreenCapLibrary#31]
Currently I am facing issue when multiple monitors are present, it is not capturing the primary monitor's video, instead it is capturing secondary monitor's video. It should ideally capture the active windows monitor's video.

**Comment by cristii006** [comment]
Hello,

The mechanism for configuring screen grabbing will be modified soon as described in #26 . This should  also fix the problems regarding what screen should be captured.

Best regards,
Cristi.

**Comment by cristii006** [comment]
Hi @msavino2,

Thank you for your contribution. For more info about contributing please see https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst.

What is done until now is good but more additions are necessary:
- First of all the changes that are required for the mss are also required for gtk.
- Second it would be nice if `windowNumber` could accept a list as an argument in case one needs to capture more screens. 

Best regards,
Cristi

**Comment by truptigogad2** [comment]
Thank you , I will try this.

**Comment by mihaiparvu** [comment]
Will be resolved with https://github.com/mihaiparvu/ScreenCapLibrary/issues/26.
