### ISSUE TITLE
0xc10100be can't play

### ISSUE THREAD

**Issue by truptigogad2** [mihaiparvu/ScreenCapLibrary#36]
I am able to capture the videos. But after the execution, when I click on the video clips saved in .webm, it gives me below error -

**Can't Play**
This file isn't playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt.
0xc10100be

Not sure, what causing this.

**Comment by mihaiparvu** [comment]
Can you give me a bit more info about your environment? Python version, OS?

Additionaly you can try ScreenCapLibrary 1.3.1 alpha 1 to see if the problem still occurs. You can install it with:

`pip install --pre --upgrade robotframework-screencaplibrary`.

**Comment by mihaiparvu** [comment]
Closing as no follow-up available on this.
