### ISSUE TITLE
Stop video recording called in the end test (robot listener) not working

### ISSUE THREAD

**Issue by TencolHu** [mihaiparvu/ScreenCapLibrary#37]
I got one issue when import ScreenCapLibrary from my robot listener py file.
Video get start to record from start_test() method and want to stop form end_test()

I just checked the output video files, just first video file can play. Another file seems didn't 
stop correctly.  File size remain 555 bytes and can't play correctly.

Could you help check if this caused by **Close Video Recording** keyword is taking time to respond. Is there any way if I want to run from listener python file and I can know start/end video is actually finished ?  Thank you so much

**Comment by mihaiparvu** [comment]
Try ScreenCapLibrary 1.3.1 alpha 1 to see if the problem still occurs. You can install it with:

`pip install --pre --upgrade robotframework-screencaplibrary`.

**Comment by TencolHu** [comment]
Cool, It works now after upgrade to 1.3.1 alpha 1. Many thanks for your answer.
