### ISSUE TITLE
Feature request: Discard Gif/Video File

### ISSUE THREAD

**Issue by AllanMedeiros** [mihaiparvu/ScreenCapLibrary#41]
Hi there.
I was searching for a way to record video during RF runs and this library seems to be the best fit.
But I want to keep and embed the gif/video file only if the test fails, avoiding wasting disk space, so could be a parameter on Stop Recording kw to discard or keep/embed the file.
Or maybe even a different kw at all, not sure what would be better.
Then it would be called from a Test or Suite Teardown.

**Comment by mihaiparvu** [comment]
Best to keep this test library as generic as possible. Adding a new argument to the keyword that is tied to the state of the running test doesn't sound like a good idea to me.

You could however easily implement this logic in your existing tests by having dedicated user keywords in Teardown section that clean up the files. The built-in variable `${TEST STATUS}` can be use to check if the test has passed or has failed.

**Comment by mihaiparvu** [comment]
`Stop Video Recording` keyword returns the created filename. And you can always post-process the results with `rebot`.
