### ISSUE TITLE
question for snapshot

### ISSUE THREAD

**Issue by davesliu** [mihaiparvu/ScreenCapLibrary#45]
Hi,
Is it possible to specify the position and size for the snapshot with this tool?

For exmaple, to capture a snapshot at coordinate (100,100) with a width 200 and hegith 150.

Thanks in advance

**Comment by mihaiparvu** [comment]
Did you try to use `Take Partial Screenshot`? It should be possible to specify to configure it to capture a screenshot  at those coordinates.

**Comment by davesliu** [comment]
Thanks for your info, I used the pyautogui to achieve the goal.
