### ISSUE TITLE
redundant embedded snapshot when using take_partial_screenshot

### ISSUE THREAD

**Issue by davesliu** [mihaiparvu/ScreenCapLibrary#56]
When using take_partial_screenshot, it will embed the screenshot twice.

It has already embedded screenshot in function take_screenshot
https://github.com/mihaiparvu/ScreenCapLibrary/blob/b5537c44c740e0f43e424fb0028dbcfd0e5b0557/src/ScreenCapLibrary/client.py#L212

https://github.com/mihaiparvu/ScreenCapLibrary/blob/b5537c44c740e0f43e424fb0028dbcfd0e5b0557/src/ScreenCapLibrary/client.py#L112

https://github.com/mihaiparvu/ScreenCapLibrary/blob/b5537c44c740e0f43e424fb0028dbcfd0e5b0557/src/ScreenCapLibrary/client.py#L228

@mihaiparvu 
Could you help to fix it by removing the redundant embedded string in HTML report?

Thanks. ###

**Comment by mihaiparvu** [comment]
Fixed in https://github.com/mihaiparvu/ScreenCapLibrary/commit/50382f33f1cee691784b3d167f466cdb691eccdb
