### ISSUE TITLE
Add possibilty to embed screenshots directly into log.html

### ISSUE THREAD

**Issue by simonmeggle** [mihaiparvu/ScreenCapLibrary#71]
Hi, 

is it possible to get screenshots only embedded into the log, but not on the filesystem?  
Thanks for this great library!
Simon

**Comment by mihaiparvu** [comment]
I think it could be possible to include the screenshots encoded in base64 directly inside the `log.html` file. Unfortunately I don't have time to implement this in the near future, so if you @simonmeggle (or anyone else) are interested in this feel free to submit a pull request.

**Comment by simonmeggle** [comment]
Thanks Mihai, I'll have a look into that.

**Comment by mihaiparvu** [comment]
Done in https://github.com/mihaiparvu/ScreenCapLibrary/commit/1fcd858e176a2cb5a381127dc8f0df5f87c2bcb6
